Fixed broadcaster and biometric, security problems
GaloyMoney/galoy-mobile pull request #220
Opened 2021-09-29 15:48 UTC by hitori666

Fixed the issue of Broadcast Receiver and biometric, this was reported used mobsf.
is necesary test to check the notifications.

2021-09-29 17:52 UTC, nicolasburtey commented
what are the binary files for?

2021-09-29 17:56 UTC, hitori666 commented
sorry was autogenerated, is not important, are empthy files, you can ignore this 2 .bin

2021-09-29 17:57 UTC, nicolasburtey commented
can you remove/rebase? we don't want binary file in our repo

2021-09-29 18:17 UTC, hitori666 commented
Done, bin files was deleted

2021-09-29 19:21 UTC, nicolasburtey commented
rebase still needed to clean up github history

independently on this I don't understand what security problem this PR fixes. more context would be useful

2021-09-29 19:28 UTC, dolcalmi requested changes

2021-09-29 19:28 UTC, dolcalmi commented on android/app/src/main/AndroidManifest.xml
> +	<!-- reciber problem security" -->
please remove this comment

2021-09-29 19:28 UTC, dolcalmi commented on android/app/src/main/AndroidManifest.xml
> +	<!-- TODO android:roundIcon="@mipmap/ic_launcher_round" -->
same here

2021-09-29 19:28 UTC, dolcalmi commented on android/app/src/main/AndroidManifest.xml
> +<!-- biometric security problem fix -->
same here

2021-09-29 19:50 UTC, hitori666 reviewed
Comments removed

2021-09-29 19:54 UTC, hitori666 commented
Rebase completed, this fixed problems that mobsf detect in the apk, one of they are Broadcast Receiver and ctivity (androidx.biometric.DeviceCredentialHandlerActivity) is not Protected. [android:exported=true], this gonna help to improve the score of the app, now we have a Average CVSS Score: 6.4, whit this change, is possible to have a better score. 
this is important for the security analisis of the app

2021-09-29 20:12 UTC, jrbuhl93 commented on android/app/src/main/AndroidManifest.xml
> +	<receiver android:exported="false" android:name="io.invertase.firebase.messaging.ReactNativeFirebaseMessagi ngReceiver" android:permission="com.google.android.c2dm.permission.SEND">
`ReactNativeFirebaseMessagi ngReceiver" ` shouldn't have a space

2021-09-29 20:14 UTC, hitori666 commented on android/app/src/main/AndroidManifest.xml
> +	<receiver android:exported="false" android:name="io.invertase.firebase.messaging.ReactNativeFirebaseMessagi ngReceiver" android:permission="com.google.android.c2dm.permission.SEND">
Done

2022-07-25 13:14 UTC, daviroo commented
This looks pretty stale to me.  Going to close it.

2022-07-25 13:14 UTC, closed without merging