Upgrade all dependencies
GaloyMoney/galoy-mobile pull request #291
Opened 2021-11-09 02:46 UTC by samerbuna

Including:

- React Navigation (major versions upgrade, some API changes)
- Firebase libraries (major versions upgrade)
- Other packages like graphql, subscription transport, vector icons (major versions upgrade)
- Other minor/patch upgrades
- All pods

Please test on Android

2021-11-09 08:30 UTC, daviroo requested changes
Other than the TODO it looks good. Also assuming that deep linking has been tested after the upgrade to the navigation library.

2021-11-09 08:30 UTC, daviroo commented on app/app.tsx
> +  // TODO: Fix this. It does not work currently
Could you add more context to the TODO? If I saw this I wouldn't know what isn't working (is it the type?). Or even better link it to an issue in GitHub.

2021-11-11 00:48 UTC, samerbuna commented
Tests pass for me locally but fail here 🤔

2021-11-12 08:47 UTC, daviroo commented
This was broken due to jest not being able to transform some of our dependency code.  I told it to ignore the `react-navigation` library and now the tests are passing. The reason the tests were failing here but not locally is that the tests here run on the pull request and there were changes from main to be rebased.

2021-11-12 08:48 UTC, daviroo approved these changes

2021-11-12 08:51 UTC, merged