Change country code to be more intuitive
GaloyMoney/galoy-mobile pull request #324
Opened 2021-12-03 17:22 UTC by BennyBlockchain

Issue [#119](https://github.com/GaloyMoney/galoy-mobile/issues/119)

Changed the component `react-native-phone-input` to `react-native-phone-number-input` because the latter was a better design to direct the user to pick a country.

2021-12-03 18:33 UTC, BennyBlockchain commented
There was also a request to add the default location to be set by the users location. I'm told the location is used in the Maps screen so it could be implemented. But, some have expressed concern asking a user for location on startup.

2021-12-03 18:44 UTC, adam-stover commented on app/screens/phone-auth-screen/phone-auth.tsx
> +  textContainer: {
move this below `text` to address the lint error from `yarn check-code`

2021-12-03 18:51 UTC, adam-stover requested changes
looks good, thanks. can you fix that comment and clean up the commit history? (squash into a single commit ahead of `main`)

2021-12-03 19:59 UTC, samerbuna requested changes
I see some changes in this PR that are not part of it. Please rebase the changes on top of the latest in the main branch

2021-12-03 20:42 UTC, samerbuna commented
I see big space between country flag and code:

<img width="403" alt="Screen Shot 2021-12-03 at 12 30 54 PM" src="https://user-images.githubusercontent.com/75209/144669153-6a1e737e-c813-4895-84fb-df352a25d61b.png">

Also, the current component allows selecting country by typing the country code. Is there a way for this component to allow typing the country code too?

2021-12-03 21:12 UTC, BennyBlockchain commented
> I see big space between country flag and code:
> 
> <img alt="Screen Shot 2021-12-03 at 12 30 54 PM" width="403" src="https://user-images.githubusercontent.com/75209/144669153-6a1e737e-c813-4895-84fb-df352a25d61b.png">
> 
> Also, the current component allows selecting country by typing the country code. Is there a way for this component to allow typing the country code too?

The component does not allow typing in the country code. I can check on the spacing if that is available to customize.

2021-12-03 21:38 UTC, BennyBlockchain commented
Rebased. Sorry for all the dumb pushes.

2021-12-03 21:48 UTC, BennyBlockchain commented
@samerbuna How does this look?
<img width="299" alt="Screen Shot 2021-12-03 at 4 47 50 PM" src="https://user-images.githubusercontent.com/77197234/144677139-181d6bd2-ace6-4f8b-b640-2f8fea8ec567.png">

2021-12-04 00:31 UTC, samerbuna commented
@BennyBlockchain I still see the space

2021-12-04 17:18 UTC, BennyBlockchain commented
@samerbuna better?
<img width="299" alt="Screen Shot 2021-12-04 at 12 18 12 PM" src="https://user-images.githubusercontent.com/77197234/144718502-8d32ad0a-543d-4184-9bde-e9804b777221.png">
am

2021-12-04 17:28 UTC, samerbuna commented
> @samerbuna better? 

I still see it on iOS. Have not tested Android yet.

2021-12-04 18:37 UTC, BennyBlockchain commented
@samerbuna Just a screenshot haven't pushed changes

2021-12-13 16:46 UTC, samerbuna commented
@BennyBlockchain I really don't like the fact that I can't select country by typing country code.

I found this library: https://github.com/MuhammedAlmaz/React-Native-INTL-Phone-Input

It would be great if we can give it a try.

2021-12-13 23:03 UTC, BennyBlockchain commented
@samerbuna & @adam-stover 

I fixed the changes requested and added unit tests for the WelcomePhoneInput screen. Could you please review.

2021-12-17 08:34 UTC, daviroo commented
Hi @BennyBlockchain.  Can you coordinate with @samerbuna to find out what changes are still required to get this merged?  Also the tests are failing.

2021-12-22 01:27 UTC, samerbuna approved these changes

2021-12-22 15:22 UTC, daviroo approved these changes
I've tested this locally on both android and ios and it's definitely an improvement on what we have.

2021-12-22 16:05 UTC, merged