Improve validation for usernameAvailable
GaloyMoney/galoy-mobile pull request #386
Opened 2022-01-16 21:21 UTC by danwebb1

- Adds "lnbc1" to the `hasNoRestictedStartCharacters` function to reduce calls to the server. 
- Adds some clarity to the forbiddenStart message letting the user know the username cannot be a bitcoin address or lightning invoice
- Adds test for "lnbc1" 

*Note - I did my best to translate the forbidden start error message which may benefit from being proofed by a native Spanish speaker. The added language may not be even be necessary and can be removed also.

2022-01-17 11:25 UTC, daviroo requested changes
Hi @danwebb1.  Thanks for the contribution.  If you have the time it would be good to make the improvements I mentioned in my comments.  If you don't have time just let me know and I can take over the PR.

2022-01-17 15:31 UTC, danwebb1 commented
> Hi @danwebb1. Thanks for the contribution. If you have the time it would be good to make the improvements I mentioned in my comments. If you don't have time just let me know and I can take over the PR.

I will make the updates/improvements this evening!

2022-01-17 16:38 UTC, nicolasburtey commented on app/i18n/en.json
> +    "forbiddenStart": "Cannot start with lnbc1, bc1, 1, or 3 and cannot be a Bitcoin address or Lightning invoice",
Email addresses will need to be working for lightning addresses

2022-01-18 16:21 UTC, daviroo commented on app/i18n/en.json
> +    "forbiddenStart": "Cannot start with lnbc1, bc1, 1, or 3 and cannot be a Bitcoin address or Lightning invoice",
@danwebb1 what @nicolasburtey is referring to is upcoming work we will do in the app to allow users to input static identifiers as outlined in the [lnurl spec](https://github.com/fiatjaf/lnurl-rfc/blob/luds/16.md).  Currently we don't support this.  If you want to leave out the email validation in anticipation of this change then that is fine with me.  Also ok if you have already implemented it as we can just remove it when we implement the above change.

2022-01-19 06:48 UTC, danwebb1 commented
https://user-images.githubusercontent.com/17483038/150078703-6331477e-4c6e-4af2-978a-cb5027c23df7.mov

2022-01-20 11:27 UTC, daviroo approved these changes

2022-01-20 11:28 UTC, merged