refactor: Enable paste lnurl
GaloyMoney/galoy-mobile pull request #392
Opened 2022-01-27 06:33 UTC by danwebb1

Send Bitcoin screen was able to handle lnurl from scanned QR code but was not able to handle user pasting lnurl directly.

- added ability to paste lnurl from send bitcoin screen 
- added clipboard icon to bottom of QR code, if user has copied it to clipboard and taps the clipboard it will paste and transition to send bitcoin screen to confirm, similar to Wallet of Satoshi and Strik

https://user-images.githubusercontent.com/17483038/151304524-8c7487ab-3a25-4be0-8e32-1bac5f83c890.mov

2022-01-27 17:31 UTC, daviroo commented
Hey @danwebb1 .  I think this PR looks good.  I haven't had time to check it out to test yet unfortunately.  My only question would be does the clipboard modal pickup that a lnurl is in the clipboard and prompt the user?  Code is here https://github.com/GaloyMoney/galoy-mobile/blob/b626cd4e757e9da7fb45699b98a2444f67f3095b/app/utils/clipboard.ts#L19.

2022-01-28 15:57 UTC, danwebb1 commented
> Hey @danwebb1 . I think this PR looks good. I haven't had time to check it out to test yet unfortunately. My only question would be does the clipboard modal pickup that a lnurl is in the clipboard and prompt the user? Code is here
> 
> https://github.com/GaloyMoney/galoy-mobile/blob/b626cd4e757e9da7fb45699b98a2444f67f3095b/app/utils/clipboard.ts#L19
> 
> .

Yes, it does pick up and alert the user. Additionally, I added slightly more specific error message to Alert on QR screen. If a lnurl-withdraw/auth/channel request is pasted instead of lnurl-pay it says that the its not currently supported instead of sayings its not a valid address.

2022-01-31 10:53 UTC, daviroo requested changes
I checked it out and tested and it works ok.  Just a few minor comments RE translations.

2022-01-31 10:53 UTC, daviroo commented on app/i18n/en.json
> +    "invalidContentLnurl": "We found:\n\n{{found}}\n\n is not currently supported"
The Spanish translation for this is missing.

2022-01-31 10:53 UTC, daviroo commented on app/i18n/en.json
> +    "invalidLnurl": "Invalid lnurl"
I don't see this being used in the actual code anywhere.

2022-01-31 10:53 UTC, daviroo commented on app/i18n/es.json
> +    "totalExceed": "total excede su saldo",
Not part of your change but I just happened to notice that this is only used in the `SendBitcoinConfirmationScreen` so I think this is an unnecessary key - could be removed.

2022-02-01 15:05 UTC, daviroo approved these changes

2022-02-01 15:05 UTC, merged