Add continue button to phone auth screen
GaloyMoney/galoy-mobile pull request #399
Opened 2022-02-25 04:25 UTC by secondl1ght

As requested in issue #390 I have added a Continue button to the phone auth screen. Now users can either use the submit button on the keyboard or they can dismiss the keyboard and hit the Continue button when they are ready. I can adjust the styling if you had something different in mind for the design.

Cheers!

Screenshot:
![image](https://user-images.githubusercontent.com/85003930/155653441-71ad0fb7-ddfc-420d-86ba-159b7c67df20.png)

2022-02-25 20:46 UTC, secondl1ght commented
I made a few updates: I added some padding to make the button a little bit bigger, I added some vertical margin so that it has more spacing during the loading screen and I also made the button disable when the phone number is set.

I want to do a bit more additional testing but I have been blocked from submitting due to too many attempts, so I will try again later.

Updated screenshot:
![image](https://user-images.githubusercontent.com/85003930/155800455-a0dde1c1-b131-45d1-8477-b9552b0ffce4.png)

2022-02-26 18:18 UTC, daviroo requested changes

2022-02-26 18:18 UTC, daviroo commented on app/i18n/en.json
> +    "continue": "Continue"
Please add this key in the `es.json` file as well.

2022-02-26 18:24 UTC, daviroo commented
Hey @secondl1ght.  We will need to add the `continue` key to the Spanish translation file otherwise the app will crash for users in El Salvador.  Also the `yarn check-code` and `yarn test` commands are failing.  Those commands will need to run successfully before we can merge.

2022-02-27 02:54 UTC, secondl1ght commented
Thanks for the review! I added the Spanish translation (I just looked it up online so hopefully it is correct) and I made sure the 2 yarn commands pass now. I just had to refactor the disabled attribute on the new button to be a boolean value in order to pass the type check.

2022-02-28 10:07 UTC, daviroo commented
> Thanks for the review! I added the Spanish translation (I just looked it up online so hopefully it is correct) and I made sure the 2 yarn commands pass now. I just had to refactor the disabled attribute on the new button to be a boolean value in order to pass the type check.

The `yarn test` command is still failing with a broken snapshot.  Did you push the changes after updating the snapshots?

2022-02-28 15:08 UTC, secondl1ght commented
> > Thanks for the review! I added the Spanish translation (I just looked it up online so hopefully it is correct) and I made sure the 2 yarn commands pass now. I just had to refactor the disabled attribute on the new button to be a boolean value in order to pass the type check.
> 
> The `yarn test` command is still failing with a broken snapshot. Did you push the changes after updating the snapshots?

After updating the snapshots there was nothing to commit so I think that file is git-ignored. It tells you in the terminal output how to fix it though - if I remember correctly you need to run the command with a flag, I believe it was `yarn test -u`.

2022-03-03 11:01 UTC, merged