feat: send bitcoin back navigation
GaloyMoney/galoy-mobile pull request #561
Opened 2022-07-13 13:46 UTC by UncleSamtoshi

- separate send-bitcoin flow into separate screens, so that it can navigate back during the flow and facilitate deeplinking

2022-07-13 14:00 UTC, daviroo reviewed
Just wanted to highlight the commented out code for now.  I'll need to check out the branch and test it locally before I can approve.

2022-07-13 20:38 UTC, UncleSamtoshi commented
This Pr addresses issues #549 #558 #536 #557

2022-07-14 11:06 UTC, daviroo requested changes
I've made some suggestions and left some comments.

2022-07-14 14:10 UTC, UncleSamtoshi commented on app/screens/send-bitcoin-screen/send-bitcoin-success-screen.tsx
> +  }, [])
Great catch!

2022-07-14 19:19 UTC, UncleSamtoshi commented on app/screens/send-bitcoin-screen/scanning-qrcode-screen.tsx
> +          // May not be neccessary any more
I'll remove it. The comment was to indicate that some of the code in the scanningQRScreen is duplicated in the sendBitcoinDestination screen. However, this is out of scope.

2022-07-15 10:27 UTC, daviroo approved these changes

2022-07-15 10:27 UTC, merged