feat: add receive usd screen title
GaloyMoney/galoy-mobile pull request #565
Opened 2022-07-14 20:40 UTC by UncleSamtoshi

- Screen title now shows "Receive USD" instead of "Receive Bitcoin" when creating a USD invoice

2022-07-14 20:41 UTC, UncleSamtoshi commented
Fixes issue #514

2022-07-15 10:31 UTC, daviroo requested changes
Just one small comment.

2022-07-15 10:31 UTC, daviroo commented on app/screens/receive-bitcoin-screen/receive-bitcoin.tsx
> +  }, [receiveCurrency])
There's some eslint warnings being generated here.  Either add the missing properties or disable the rule for this line.

2022-07-15 13:55 UTC, daviroo approved these changes

2022-07-15 18:16 UTC, merged