fix: test to check if country picker is visible was recreated
GaloyMoney/galoy-mobile pull request #568
Opened 2022-07-15 14:21 UTC by eimolina

I recreated a test that had problems. I extracted the same code that uses the "PhoneInput" component, to have a component with the TestID field and be able to use it in the test.
Ref https://github.com/GaloyMoney/galoy-mobile/issues/430

2022-07-25 14:05 UTC, eimolina commented
hi, @daviroo. Can you review this PR and if there are some changes to do, please let me know. tanks.

2022-07-27 02:45 UTC, samerbuna requested changes

2022-07-27 02:45 UTC, samerbuna commented on __tests__/screens/phone-auth.spec.tsx
> +    const { UNSAFE_queryByType, getByTestId } = render(
`UNSAFE_queryByType` is not used

2022-07-27 02:45 UTC, samerbuna commented on app/screens/phone-auth-screen/phone-auth.tsx
> +    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAi0lEQVRYR+3WuQ6AIBRE0eHL1T83FBqU5S1szdiY2NyTKcCAzU/Y3AcBXIALcIF0gRPAsehgugDEXnYQrUC88RIgfpuJ+MRrgFmILN4CjEYU4xJgFKIa1wB6Ec24
Can we make this into an SVG?

2022-07-27 05:35 UTC, eimolina commented on app/screens/phone-auth-screen/phone-auth.tsx
> +    "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAi0lEQVRYR+3WuQ6AIBRE0eHL1T83FBqU5S1szdiY2NyTKcCAzU/Y3AcBXIALcIF0gRPAsehgugDEXnYQrUC88RIgfpuJ+MRrgFmILN4CjEYU4xJgFKIa1wB6Ec24
Yes, we can.

2022-07-27 05:36 UTC, eimolina commented on __tests__/screens/phone-auth.spec.tsx
> +    const { UNSAFE_queryByType, getByTestId } = render(
sorry, my bad.

2022-07-30 18:10 UTC, samerbuna approved these changes
Thank you!

2022-07-30 18:10 UTC, merged