chore: improve error handling
GaloyMoney/galoy-mobile pull request #653
Opened 2022-10-17 14:11 UTC by UncleSamtoshi

- record caught errors with crashlytics
- add script to symbolicate crashlytics trace
- prevent updating state during render for globar-error component
- rename contacts screen to prevent nested naming

2022-11-01 15:01 UTC, daviroo requested changes

2022-11-01 15:01 UTC, daviroo commented on app/navigation/root-navigator.tsx
> +        name="contactList"
There's also a reference to `"Contacts"` on line `564`.  Should we change that as well?

2022-12-06 21:39 UTC, UncleSamtoshi commented on .circleci/config.yml
> +      - run: gh release upload $CIRCLE_TAG "android/app/build/generated/sourcemaps/react/release/index.android.bundle.map" --clobber
This publishes the source map so that we can link js errors to their location in typescript

2022-12-07 15:53 UTC, daviroo approved these changes

2022-12-15 21:28 UTC, merged