feat: Added new currency input
GaloyMoney/galoy-mobile pull request #745
Opened 2022-12-23 11:05 UTC by daviroo

2022-12-28 16:53 UTC, daviroo commented
After speaking with @UncleSamtoshi we are going to go in a slightly different direction with this.  We will look to replicate the logic from galoy-pay which uses a reducer to control the value displayed in the currency input.  Have moved to draft for now so I can make some changes.

2023-01-02 21:21 UTC, UncleSamtoshi requested changes

2023-01-10 13:07 UTC, daviroo commented on app/hooks/use-price-conversion.ts
> +  const convertDisplayAmount = React.useCallback(
I think we would want to keep these separate as we discussed on the call last week.  The main point is we want to have a way of defining a `primaryCurrency` for a payment flow (which could have a `DisplayCurrency` or a `WalletCurrency`) so we can offer a recalculation of the amount at some point in the flow (if the price changes).

2023-01-10 13:11 UTC, nicolasburtey commented on app/components/atomic/galoy-icon/galoy-icon.tsx
> +  "switch-currency": SwitchCurrency,
Should it be the same design?

2023-01-10 13:13 UTC, daviroo commented on app/types/amounts.ts
> +  precision?: number
The display values have been removed as we discussed.

2023-01-10 13:13 UTC, daviroo commented on app/components/currency-input/currency-input-state.tsx
> +  type: string
This is done now.

2023-04-01 11:49 UTC, closed without merging