chore: rotate tokens for e2e tests
GaloyMoney/galoy-mobile pull request #905
Opened 2023-01-17 14:50 UTC by Extheoisah

2023-01-17 17:44 UTC, nicolasburtey commented on e2e/utils/graphql.ts
> +const randomizeTokens = (arr: string[]): string => {
this function is overly complicated.

here is chatGPT rewrite of the function:

```
const randomizeTokens = (arr: string[]): string => {
  const randomIndex = Math.floor(Math.random() * arr.length);
  return arr[randomIndex];
}
```

2023-01-18 09:08 UTC, nicolasburtey commented on e2e/utils/graphql.ts
> +console.log(firstAuthToken, secondAuthToken)
to be removed

2023-01-19 20:37 UTC, Extheoisah commented on e2e/utils/graphql.ts
> +  let secondAuthToken = randomizeTokens(authTokens)
Yeah, resolved

2023-01-19 22:10 UTC, UncleSamtoshi requested changes

2023-01-19 22:10 UTC, UncleSamtoshi commented on e2e/utils/graphql.ts
> +export const firstAuthToken = randomizeTokens(authTokens)
I would rename these to be more specific,  such as `mobileUserToken` and secondAuthToken to be `recieverToken`

2023-01-19 22:23 UTC, UncleSamtoshi commented on e2e/utils/graphql.ts
> +const recieverToken = process.env.GALOY_TOKEN_2 || ""
Oh shoot my bad for the typo but it should be `receiver`

2023-01-19 22:46 UTC, UncleSamtoshi approved these changes

2023-01-19 22:48 UTC, merged