chore: removing another use of apolloClient and use the mutation instead
GaloyMoney/galoy-mobile pull request #916
Opened 2023-01-18 14:57 UTC by nicolasburtey

2023-01-21 14:19 UTC, nicolasburtey commented on app/navigation/root-navigator.tsx
> +  useAddDeviceToken()
not needed?

2023-01-24 18:30 UTC, UncleSamtoshi requested changes

2023-01-24 18:30 UTC, UncleSamtoshi commented on app/navigation/root-navigator.tsx
> +        messaging().onTokenRefresh(useAddDeviceToken)
Hooks need to run on every render, I dont believe they can be used in a useEffect which happens outside of a render cycle and only when its dependencies change.

2023-01-24 18:30 UTC, UncleSamtoshi commented on app/navigation/root-navigator.tsx
> +  useAddDeviceToken()
I believe this will call addDeviceToken on every render.

2023-02-06 11:03 UTC, daviroo commented
@nicolasburtey this needs rebased

2023-02-15 23:26 UTC, closed without merging